version: '3.9'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=mosswn1234
      - DATABASE_NAME=mydb
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mosswn1234
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: KOUY.baber@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mosswn1234
    ports:
      - '5050:80'
    restart: always

volumes:
  pgdata:
